[connections.supabase]
SUPABASE_URL = "https://mhbkszhwogjixbzmecdi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oYmtzemh3b2dqaXhiem1lY2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NDI0NTgsImV4cCI6MjA4NTAxODQ1OH0.R-k7lhbvXS1RcpNlixuSGDjGPh-FbptR-h5ho-gG8jQ"